JofApp/Areas/Manage/Controllers/FruitsController.cs
using JofApp.Areas.Manage.ViewModels;
using JofApp.DAL;
using JofApp.Helpers;
using JofApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JofApp.Areas.Manage.Controllers
{
    [AutoValidateAntiforgeryToken]
    [Authorize(Roles ="Admin")]
    [Area("Manage")]
    public class FruitsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public FruitsController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        public async Task<IActionResult> Index()
        {
            var fruits = await _context.Fruits.ToListAsync();
            return View(fruits);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateFruitVm createFruitVm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Fruits newFruit = new Fruits()
            {
                Name = createFruitVm.Name,
                Category = createFruitVm.Category,
                ImgUrl = createFruitVm.File.Upload(_environment.WebRootPath, @"/Upload/")
            };

            var result = await _context.Fruits.AddAsync(newFruit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> Update(int id)
        {

            Fruits fruit = await _context.Fruits.FindAsync(id);
            UpdateFruitVm updateFruitVm = new UpdateFruitVm()
            {
                Id = fruit.Id,
                Name = fruit.Name,
                Category= fruit.Category               
            };
            return View(updateFruitVm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateFruitVm updateFruitVm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var oldFruit = await _context.Fruits.FirstOrDefaultAsync(c => c.Id == updateFruitVm.Id);
            if (updateFruitVm.File != null)
            {
                oldFruit.ImgUrl.DeleteFile(_environment.WebRootPath, @"/Upload/");
                oldFruit.ImgUrl=updateFruitVm.File.Upload(_environment.WebRootPath, @"/Upload/");
            }

            oldFruit.Name = updateFruitVm.Name;
            oldFruit.Category = updateFruitVm.Category;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(int id)
        {
            var oldFruit = _context.Fruits.FirstOrDefault(c => c.Id == id);
            _context.Fruits.Remove(oldFruit);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

JofApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Jof</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="~/images/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header id="home">
        <!-- header inner -->
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo"> <a href="index.html"><img src="~/images/logo.png" alt="#"></a> </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <div class="menu-area">
                            <div class="limit-box">
                                <nav class="main-menu">
                                    <ul class="menu-area-main">
                                        <li class="active"><a href="#home">Home</a></li>
                                        <li><a href="#about">About Us</a></li>
                                        <li><a href="#fruits">Fruits</a></li>
                                        @if(User.Identity.Name=="Emil23"){

                                        <li><a asp-area="Manage" asp-action="Index" asp-controller="Fruits">Products</a></li>
                                        }
                                        @if(!User.Identity.IsAuthenticated)
                                        {
                                        <li>
                                            <a asp-action="Login" asp-controller="Account">Login </a>
                                            <a asp-action="Register" asp-controller="Account">Register </a>
                                            </li>

                                        }
                                        else{
                                            <li>
                                                <a asp-action="LogOut" asp-controller="Account">LogOut </a>
                                                <a>@User.Identity.Name </a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end header inner -->
    </header>
    <!-- end header -->
    @RenderBody()



    <!-- footer -->
    <footer>
        <div class="footer layout_padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <h3>Contact Us</h3>
                        <p>Healing Center, 176 W Street name, New York, NY<br><br>(+91) 987 654 3210<br><br>demo@gmail.com</p>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <h3>Pages</h3>
                        <p>
                            <a href="#home">Home</a><br>
                            <a href="#about">About Us</a><br>
                            <a href="#fruits">Fruits</a><br>
                            <a href="#blog">Blog</a><br>
                            <a href="#contact">Contact Us</a>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <h3>Recent Post</h3>
                        <p><span><img src="~/images/f_b1.png"></span><span>consectetur adipisc elit,<br>sed do eiusmod</span></p>
                        <p class="margin_top_20"><span><img src="~/images/f_b2.png"></span><span>consectetur adipisc elit,<br>sed do eiusmod</span></p>
                        <p class="margin_top_20"><span><img src="~/images/f_b3.png"></span><span>consectetur adipisc elit,<br>sed do eiusmod</span></p>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12">
                        <h3>Newsletter</h3>
                        <p>
                            <form>
                                <input type="text" name="email" placeholder="Enter Your Email" />
                                <button>Subscribe</button>
                            </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <p>Copyright 2019 All Right Reserved By <a href="https://html.design/">Free html Templates</a></p>
            </div>
        </div>
    </footer>
    <!-- end footer -->
    <!-- Javascript files-->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.0.0.min.js"></script>
    <script src="~/js/plugin.js"></script>

    <!-- sidebar -->
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/custom.js"></script>
</body>

</html>